# Generated by Django 2.1.2 on 2018-10-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20181024_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='left',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='right',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.Game'),
        ),
    ]
